import * as THREE from "three";
import { ModelLoader } from "./ModelLoader";

/**
 * Loads character GLBs (generated by TripoSR) and patches them so they
 * actually render properly:
 *
 *  1. TripoSR outputs vertex colors (COLOR_0) but no material assignment —
 *     Three.js falls back to a default material with vertexColors=false so
 *     the model looks uniformly dark. We assign a MeshStandardMaterial with
 *     vertexColors=true to bring the painted colors through.
 *
 *  2. TripoSR doesn't emit per-vertex normals, so directional lighting
 *     can't shade the surface. We compute them with computeVertexNormals.
 *
 *  3. TripoSR centres the mesh around its bbox centre (feet at -0.5, head
 *     at +0.5 roughly), so placing the model at world y=0 buries it half
 *     in the floor. We translate up by -bbox.min.y so feet land on y=0.
 */
export class CharacterLoader {
  private readonly modelLoader: ModelLoader;
  private readonly characterScale: number;

  constructor(modelLoader: ModelLoader, characterScale = 1.7) {
    this.modelLoader = modelLoader;
    this.characterScale = characterScale;
  }

  async load(characterId: string): Promise<THREE.Group> {
    const root = await this.modelLoader.load(`assets/characters/${characterId}.glb`);
    this.patchMaterials(root);
    this.computeNormalsIfMissing(root);
    this.liftFeetToOrigin(root);
    root.scale.setScalar(this.characterScale);
    return root;
  }

  /** Replace TripoSR's missing material with one that honours vertex colors. */
  private patchMaterials(root: THREE.Object3D): void {
    root.traverse((obj) => {
      if (!(obj instanceof THREE.Mesh)) return;
      const geom = obj.geometry as THREE.BufferGeometry;
      const hasColor = geom.getAttribute("color") != null;
      // Replace whatever material Three.js auto-assigned with one that
      // explicitly uses vertex colors and has reasonable PBR defaults.
      obj.material = new THREE.MeshStandardMaterial({
        vertexColors: hasColor,
        // Without vertex colors fall back to a warm neutral so the model is
        // still visible (just won't be the original AI-rendered colors).
        color: hasColor ? 0xffffff : 0xe6c9a0,
        roughness: 0.85,
        metalness: 0.0,
        // TripoSR meshes are single-sided but the back face is often the
        // "hollow" side — render both sides so we don't see through them
        // from unusual angles.
        side: THREE.DoubleSide,
      });
      obj.castShadow = true;
      obj.receiveShadow = true;
    });
  }

  private computeNormalsIfMissing(root: THREE.Object3D): void {
    root.traverse((obj) => {
      if (!(obj instanceof THREE.Mesh)) return;
      const geom = obj.geometry as THREE.BufferGeometry;
      if (!geom.getAttribute("normal")) {
        geom.computeVertexNormals();
      }
    });
  }

  private liftFeetToOrigin(root: THREE.Object3D): void {
    // World matrix may not be up to date yet — force compute.
    root.updateWorldMatrix(true, true);
    const bbox = new THREE.Box3().setFromObject(root);
    if (Number.isFinite(bbox.min.y)) {
      root.position.y -= bbox.min.y;
    }
  }
}
